cluster('{{ .ClusterURI }}').database('{{ .ServiceDatabase }}').table('clustersServiceLogs')
| where timestamp between ({{ kqlDatetime .StartTime }} .. {{ kqlDatetime .EndTime }})
| where cid == '{{ .ClusterID }}'
| where log.msg has 'creating maestro bundle with maestro bundle name'
| project manifestWork = extract("containing resource '([^']+)'", 1, tostring(log.msg))
| where isnotempty(manifestWork)
| distinct manifestWork
