cluster('{{ .ClusterURI }}').database('{{ .ServiceDatabase }}').table('backendLogs')
| where timestamp between ({{ kqlDatetime .StartTime }} .. {{ kqlDatetime .EndTime }})
| where container_name == 'aro-hcp-backend'
| where log.controller_name == 'datadump'
| where log.content.resourceId =~ '{{ .AsyncOperationId }}'
| summarize take_any(log.content) by tostring(log.content.lastTransitionTime)
| sort by log_content_lastTransitionTime asc
| project log_content
