cluster('{{ .ClusterURI }}').database('{{ .ServiceDatabase }}').table('containerLogs')
| where timestamp between ({{ kqlDatetime .StartTime }} .. {{ kqlDatetime .EndTime }})
| where namespace_name == 'maestro'
| where container_name == 'maestro-server'
| where {{ range $i, $id := .BundleIDs }}{{ if $i }} or {{ end }}log contains '"resourceid":"{{ $id }}"'{{ end }}
| where log !contains 'send the event to status subscribers'
| extend bundleId = extract('"resourceid":"([^"]+)"', 1, tostring(log))
| extend message = extract('] "([^"]+)"', 1, tostring(log))
| project timestamp, bundleId, message
| order by timestamp asc
