cluster('{{ .ClusterURI }}').database('{{ .ServiceDatabase }}').table('backendLogs')
| where timestamp between ({{ kqlDatetime .StartTime }} .. {{ kqlDatetime .EndTime }})
| where container_name == 'aro-hcp-backend'
| where log.controller_name == 'datadump'
| where log.controllerKey.resourceGroupName == '{{ .ResourceGroup }}'
| where log.controllerKey.hcpClusterName == '{{ .ResourceName }}'
| where log.content.resourceType =~ '{{ .ResourceType }}'
| distinct tostring(log.content.properties.internalId)
