cluster('{{ .ClusterURI }}').database('{{ .ServiceDatabase }}').table('frontendLogs')
| where timestamp between ({{ kqlDatetime .StartTime }} .. {{ kqlDatetime .EndTime }})
| where log.correlation_request_id == '{{ .CorrelationID }}'
| where log.msg == 'response complete'
| where log.method == 'put' or log.method == 'post'
| project asyncOperationPath = tolower(tostring(parse_url(tostring(log["Header---Azure-AsyncOperation"])).Path))
| limit 1
