cluster('{{ .ClusterURI }}').database('{{ .ServiceDatabase }}').table('backendLogs')
| where timestamp between ({{ kqlDatetime .StartTime }} .. {{ kqlDatetime .EndTime }})
| where container_name == 'aro-hcp-backend'
| where log.controller_name == 'datadump'
| where log.content.resourceID =~ '{{ .ResourceID }}'
| summarize take_any(log.content) by tostring(log.content._etag)
| sort by tolong(log_content._ts) asc
| project log_content
