cluster('{{ .ClusterURI }}').database('{{ .ServiceDatabase }}').table('backendLogs')
| where timestamp between ({{ kqlDatetime .StartTime }} .. {{ kqlDatetime .EndTime }})
| where container_name == 'aro-hcp-backend'
| where log.controller_name == 'datadump'
| where log.resource_group == '{{ .ResourceGroup }}'
| where log.resource_name == '{{ .ClusterResourceName }}'
| where log.content.resourceType =~ 'microsoft.redhatopenshift/hcpopenshiftclusters/nodepools/managementclustercontents'
| summarize take_any(log.content) by tostring(log.content._etag)
| sort by tolong(log_content._ts) asc
| extend content = parse_json(log_content)
| mv-expand manifest = content.properties.status.kubeContent.items
| where manifest.kind == 'NodePool'
| mv-expand condition = manifest.status.conditions
| project condition.type, condition.status, condition.reason, condition.message, todatetime(condition.lastTransitionTime)
| distinct tostring(condition_type), tostring(condition_status), tostring(condition_reason), tostring(condition_message), todatetime(condition_lastTransitionTime)
| order by condition_lastTransitionTime asc
