cluster('{{ .ClusterURI }}').database('{{ .ServiceDatabase }}').table('backendLogs')
| where timestamp between({{ kqlDatetime .StartTime }} .. {{ kqlDatetime .EndTime }})
| where container_name == 'aro-hcp-backend'
| where log.controllerKey.resourceGroupName == '{{ .ResourceGroup }}'
| where log.msg has 'dumping resourceID' and log.msg has 'hcpOpenShiftControllers'
| extend controller_name = extract("/hcpOpenShiftControllers/([^\\/]+)", 1, tostring(log.currentResourceID))
| mv-expand condition = log.content.properties.status.conditions
| project condition.lastTransitionTime, controller_name, condition.type, condition.status, condition.reason, condition.message