let _cs_cluster_id = toscalar(
    cluster('{{ .ClusterURI }}').database('{{ .ServiceDatabase }}').table('clustersServiceLogs')
    | where timestamp between({{ kqlDatetime .StartTime }} .. {{ kqlDatetime .EndTime }})
    | where resource_id has '{{.ResourceGroup}}'
    | where isnotempty(cid)
    | distinct tostring(cid)
    | limit 1
);
cluster('{{ .ClusterURI }}').database('{{ .ServiceDatabase }}').table('clustersServiceLogs')
| where timestamp between({{ kqlDatetime .StartTime }} .. {{ kqlDatetime .EndTime }})
| where cid == _cs_cluster_id
| where log.opid == '{{ .Extra.opid }}'
| project timestamp, log.msg