let _cs_cluster_id = toscalar(
    cluster('{{ .ClusterURI }}').database('{{ .ServiceDatabase }}').table('clustersServiceLogs')
    | where timestamp between({{ kqlDatetime .StartTime }} .. {{ kqlDatetime .EndTime }})
    | where resource_id has '{{.ResourceGroup}}'
    | where isnotempty(cid)
    | distinct tostring(cid)
    | limit 1
);
cluster('{{ .ClusterURI }}').database('{{ .ServiceDatabase }}').table('clustersServiceLogs')
| where timestamp between({{ kqlDatetime .StartTime }} .. {{ kqlDatetime .EndTime }})
| where resource_id has '{{.ResourceGroup}}'
| where msg has 'ManifestWork for cluster'
| extend manifest_work = parse_json(replace_string(tostring(msg), strcat("ManifestWork for cluster '",_cs_cluster_id, "': "), ""))
| mv-expand manifest = manifest_work.status.resourceStatus.manifests
| where manifest.resourceMeta.kind == 'HostedCluster'
| mv-expand condition = manifest.statusFeedback.values
| extend condition_name = extract(@"^([^-]+)", 1, tostring(condition.name))
| extend condition_field = extract(@"([^-]+)$", 1, tostring(condition.name))
| where condition_field in ("Reason", "Status", "Message")
| project timestamp, condition_name, condition_field, condition_value = tostring(condition.fieldValue.['string'])
