cluster('{{ .ClusterURI }}').database('{{ .ServiceDatabase }}').table('backendLogs')
| where timestamp between ({{ kqlDatetime .StartTime }} .. {{ kqlDatetime .EndTime }})
| where container_name == 'aro-hcp-backend'
| where log.controller_name == 'datadump'
| where log.controllerKey.resourceGroupName == '{{ .ResourceGroup }}'
| where log.controllerKey.hcpClusterName == '{{ .ResourceName }}'
| where log.content.resourceType =~ 'microsoft.redhatopenshift/hcpopenshiftclusters/managementclustercontents'
| summarize take_any(log.content) by tolong(log.content._ts)
| extend content = parse_json(log_content)
| mv-expand manifest = content.properties.status.kubeContent.items
| where manifest.kind == 'HostedCluster'
| extend hostedClusterNamespace = strcat(manifest.metadata.namespace, "-", manifest.metadata.name)
| distinct hostedClusterNamespace
